//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SimOWS.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIMOWS_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_FHPARAM                     129
#define IDD_TESTPARAM                   130
#define IDR_MENU_MAIN                   130
#define IDD_INPUTTH                     131
#define IDD_INPUT1                      132
#define IDD_BEDCOORD                    133
#define IDD_INIT_ACS                    134
#define IDD_BEDRELATE_PARAM             136
#define IDD_AUTOACQ_COINTIME            137
#define IDR_POPUP                       138
#define IDD_BUCKETPARAM                 138
#define IDD_AUTOACQ_BUCKET              139
#define IDR_PAL_MAP                     140
#define IDR_PAL_HOT                     141
#define IDR_COINTIME                    141
#define IDR_ENERGY                      142
#define IDR_PAL_FLOW                    143
#define IDR_SD                          143
#define IDR_PAL_NIH                     144
#define IDR_TIME                        144
#define IDD_FHPOSPARAM                  145
#define IDC_START                       1000
#define IDC_STOP                        1001
#define IDC_EDIT1                       1002
#define IDC_DBGSHOW                     1002
#define IDC_RING                        1002
#define IDC_TIME_INSTANT                1002
#define IDC_BUCKET_BEGIN                1002
#define IDC_ENERGYMODE                  1003
#define IDC_EDIT_UTH                    1003
#define IDC_TIME_MIN                    1003
#define IDC_ENERGYMODE2                 1004
#define IDC_EDIT_LTH                    1004
#define IDC_TIME_MAX                    1004
#define IDC_ENERGYMODE3                 1005
#define IDC_EDIT_WORD                   1005
#define IDC_ECG_PREAMP                  1005
#define IDC_ENERGYMODE4                 1006
#define IDC_RADIO1                      1006
#define IDC_FOV                         1007
#define IDC_STOPONCNT                   1008
#define IDC_STOPONTIME                  1009
#define IDC_STOPONUSER                  1010
#define IDC_EVENTCNT                    1011
#define IDC_STOP_EVENTCNT               1011
#define IDC_STOP_TIME                   1012
#define IDC_TIPS_ACQ                    1013
#define IDC_WORKMODE_DEBUG              1014
#define IDC_TIPS_MC                     1014
#define IDC_WORKMODE_FH                 1015
#define IDC_TIPS_SYSINFO                1015
#define IDC_COMBO1                      1016
#define IDC_BUCKET                      1016
#define IDC_IN                          1016
#define IDC_RODSPEED                    1016
#define IDC_ECG_SAMPLEFREQ              1016
#define IDC_TIPS_MONITOR                1016
#define IDC_DATFMT                      1017
#define IDC_LEN                         1017
#define IDC_RADIO2                      1018
#define IDC_RADIO3                      1019
#define IDC_RADIO4                      1020
#define IDC_SCANMODE                    1022
#define IDC_SCANMODE1                   1023
#define IDC_SCANMODE2                   1024
#define IDC_DISP_GATE                   1025
#define IDC_DISP_ROD                    1026
#define IDC_DISP_BUCK                   1027
#define IDC_SCANMODE3                   1028
#define IDC_UPB                         1031
#define IDC_LBP                         1032
#define IDC_FORWORD_RR_NUM              1033
#define IDC_BACKWORD_RR_NUM             1034
#define IDC_FORWORD_RR_PER              1035
#define IDC_BACKWORD_RR_PER             1036
#define IDC_GATEMODE                    1037
#define IDC_DISP_LMD                    1038
#define IDC_COIN_FMT_POS                1039
#define IDC_COIN_FMT_TIME               1040
#define IDC_EN_EMC                      1042
#define IDC_EN_DBGBUCKET                1043
#define IDC_DEFAULT                     1044
#define IDC_RODENABLE                   1045
#define IDC_EN_EMC2                     1045
#define IDC_EN_BUCKETSIO                1045
#define IDC_SEPTAENABLE                 1046
#define IDC_COIN_POS                    1047
#define IDC_COIN_TIME                   1048
#define IDC_COIN_BUCKET                 1049
#define IDC_RODRATE1                    1050
#define IDC_RODRATE2                    1051
#define IDC_RODRATE3                    1052
#define IDC_BUCKET_TIME                 1054
#define IDC_BUCKET_MODE                 1055
#define IDC_BUCKET_END                  1056
#define IDC_SAVEPATH                    1057
#define IDC_AUTOACQ_COINTIME            1058
#define IDC_ROD_IN                      1059
#define IDC_ROD_OUT                     1060
#define IDC_SEPTA_IN                    1061
#define IDC_SEPTA_OUT                   1062
#define IDC_ACQ_BUCKET                  1063
#define IDC_DAT_SD                      1064
#define IDC_DAT_ENERGY                  1065
#define IDC_DAT_TIME                    1066
#define IDC_BROWN                       1067
#define IDC_ACQ_COINPOS                 1068
#define IDC_AUTOACQ_BUCKET              1069
#define IDC_ACQ_COINTIME                1070
#define IDC_INITACS                     1071
#define IDM_QUERY_TG                    32771
#define IDM_PAL2_256                    32771
#define IDM_MAINWND                     32772
#define IDM_CTRL_RODOUT                 32772
#define IDM_PAL_MAP                     32773
#define IDM_CTRL_BEDMOVEX               32773
#define IDM_SAVE2                       32773
#define IDM_PAL1_MAP                    32773
#define IDM_PAL_DEFAULT                 32774
#define IDM_QUERY_TW                    32774
#define IDM_PAL2_DEFAULT                32774
#define IDM_PAL_HOT                     32775
#define IDM_QUERY_V                     32775
#define IDM_1D                          32775
#define IDM_PAL1_HOT                    32775
#define IDM_QUERY_I                     32776
#define IDM_2D                          32776
#define IDM_QUERY_TH_V                  32777
#define IDM_QUERY_TH_I                  32778
#define IDM_PAL2_MAP                    32778
#define IDM_PAL1_DEFAULT                32778
#define IDM_QUERY_TH_TW                 32779
#define IDM_PAL1_256                    32779
#define IDM_PAL_FLOW                    32780
#define IDM_QUERY_TH_TG                 32780
#define IDM_PAL2_FLOW                   32780
#define IDM_PAL_NIH                     32781
#define IDM_SET_TH_TG                   32781
#define IDM_PAL2_NIH                    32781
#define IDM_SET_TH_TW                   32782
#define IDM_PAL1_FLOW                   32782
#define IDM_SET_TH_V                    32783
#define IDM_PAL1_NIH                    32783
#define IDM_SET_TH_I                    32784
#define IDM_PAL2_HOT                    32784
#define IDM_CTRL_SEPTAOUT               32785
#define IDM_SAVE1                       32785
#define IDM_QUERY_BED_POS               32786
#define IDM_SAVE                        32786
#define IDM_QUERY_BED_STEP              32787
#define IDM_SET_RODRATE                 32788
#define IDM_QUERY_ROD_RATE              32789
#define IDM_CTRL_BEDMOVEY               32790
#define IDM_CTRL_BEDMOVESTEPX           32791
#define IDM_CTRL_BEDMOVESTEPY           32792
#define IDM_CTRL_BEDSTOPX               32793
#define IDM_CTRL_BEDSTOPY               32794
#define IDM_CTRL_BEDSTOPALL             32795
#define IDM_CTRL_SEPTASTOP              32796
#define IDM_CTRL_SEPTAIN                32797
#define IDM_CTRL_RODIN                  32798
#define IDM_CTRL_RODSTOP                32799
#define IDM_SET_BEDCOORD                32800
#define IDM_SET_BEDSTEP                 32801
#define IDM_CTRL_LASERON                32802
#define IDM_CTRL_LASEROFF               32803
#define IDM_CTRL_MPOWER_ON              32804
#define IDM_CTRL_MPOWER_OFF             32805
#define IDM_CTRL_HV_OFF                 32806
#define IDM_CTRL_HV_ON                  32807
#define IDM_QUERY_BED_MOVESTATUS        32808
#define IDM_QUERY_BED_SWITCHSET         32809
#define IDM_QUERY_ROD_SWITCHSET         32810
#define IDM_QUERY_SEPTA_SWITCHSET       32811
#define IDM_CTRL_SEPTAESTOP             32812
#define IDM_CTRL_RODESTOP               32813
#define IDM_QUERY_TBED                  32814
#define IDM_QUERY_TROD                  32815
#define IDM_QUERY_TSEPTA                32816
#define IDM_DBG_POLLENABLE              32817
#define IDM_DBG_POLLDISABLE             32818
#define IDM_CTRL_BEDMOVEX_RELATE        32819
#define IDM_CTRL_BEDMOVEY_RELATE        32820
#define IDM_QUERY_ROD_STATUS            32821
#define IDM_QUERY_SEPTA_STATUS          32822
#define IDM_CTRL_RODROLL                32823
#define IDM_QUERY_HVSTATUS              32824
#define IDM_TESTMODE                    32825
#define IDM_BUCKETALL                   32826
#define IDM_BUCKET0                     32827
#define IDM_BUCKET1                     32828
#define IDM_BUCKET2                     32829
#define IDM_BUCKET3                     32830
#define IDM_BUCKET4                     32831
#define IDM_BUCKET5                     32832
#define IDM_BUCKET6                     32833
#define IDM_BUCKET7                     32834
#define IDM_BUCKET8                     32835
#define IDM_BUCKET9                     32836
#define IDM_BUCKET10                    32837
#define IDM_BUCKET11                    32838
#define IDM_BUCKET12                    32839
#define IDM_BUCKET13                    32840
#define IDM_BUCKET14                    32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
