//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Maint.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAINTTYPE                   129
#define IDD_SHOWBAR                     130
#define IDD_COMMSET                     131
#define IDD_DATA_SAMPLE                 134
#define IDD_ENVIRMENTPARAM              136
#define IDD_FPGA_BOARDLOCAL             138
#define IDD_FPGA_BOARDENER              141
#define IDD_FPGA_TIMEMODFY              143
#define IDD_FPGA_CYSNUM                 145
#define IDD_FPGA_TSERIES                147
#define IDD_ANLOG                       149
#define IDD_DIALOG1                     152
#define IDB_BITMAP2                     155
#define IDD_LOGIN                       156
#define IDD_SFLASH                      157
#define IDB_SFLASH                      158
#define IDB_IMAGE1                      159
#define IDI_ZHIZI                       160
#define IDR_MENU_SHOWENERGE             163
#define IDD_FPGA_COUNTER                164
#define IDD_FILESAVE                    166
#define IDD_MODELESS                    172
#define IDD_DIALOG2                     173
#define IDD_EFFECT_STAT                 174
#define IDB_BACKGROUND                  176
#define IDD_ANOL_PARA_MANUL_MODIFY      178
#define IDD_AUTOSAMPLE_OPTION           180
#define IDD_FPGA_COUNT_MAP              181
#define IDD_ABOUT                       183
#define IDD_SET64ENERGELIMIT_PARA       184
#define IDD_ENVIRMENT_LIMIT             185
#define IDC_SHOWBAR_3D_RADIO            1000
#define IDC_SHOWBAR_2D_RADIO            1001
#define IDC_2D_SHOW_X                   1002
#define IDC_2D_SHOW_Y                   1003
#define IDC_2D_SHOW_OFFSET1             1004
#define IDC_3D_SHOW_THREVALUE           1005
#define IDC_REDRAW                      1007
#define IDC_COMBO_BAUDSEL               1009
#define IDC_COMBO_DATABIT               1010
#define IDC_COMBO_STOPBIT               1011
#define IDC_COMBO_CRCBIT                1012
#define IDC_COMBO_PORTSET               1013
#define IDOKe                           1014
#define IDC_CANCEL                      1015
#define IDC_RADIO_SDOT                  1016
#define IDC_RADIO_EDOT                  1017
#define IDC_RADIO_TDOT                  1018
#define IDC_RADIO_FUHE0                 1019
#define IDC_RADIO_FUHE1                 1020
#define IDC_BUCKET_SEL                  1021
#define IDC_BLOCK_SEL                   1022
#define IDC_SETCOUNT                    1023
#define IDC_SETTIME                     1024
#define IDC_REC_COUNT                   1025
#define IDC_STOP_SAMPLE                 1026
#define IDC_START_SAMPLE                1027
#define IDC_COUNTER_REDRAW              1028
#define IDC_MSCOMM                      1029
#define IDC_VALI_STATIC                 1031
#define IDC_NVALI_STATIC                1032
#define IDC_THEM_STATIC                 1033
#define IDC_MSCOMM1                     1034
#define IDC_BUTT_START_QUERY            1035
#define IDC_STATIC_RECSTATUS            1036
#define IDC_EEPROM_RADIO                1040
#define IDC_FPGA_RADIO                  1041
#define IDC_INPUT_RADIO                 1042
#define IDC_OUTPUT_RADIO                1043
#define IDC_MSFLEXGRID1                 1044
#define IDC_BOARDLOCAL_EDIT             1045
#define IDC_BOARDENERG_EDIT             1046
#define IDC_TIMEMODFY_EDIT              1048
#define IDC_CYSNUM_EDIT                 1049
#define IDC_TSERIES_EDIT                1050
#define IDC_COMBO1                      1051
#define IDC_COMBO_SELOBJECT             1051
#define IDC_EDIT1                       1052
#define IDC_PLUS_A                      1052
#define IDC_OLDVALUE_LIMIT              1052
#define IDC_USER                        1052
#define IDC_TMOD_INIT_VALUE             1052
#define IDC_CHANNEL0_ALL                1052
#define IDC_PEAKVALE_ETH                1052
#define IDC_ENPARA_SHOW                 1052
#define IDC_START_POINT                 1052
#define IDC_EDIT_START_FILE             1052
#define IDC_EDIT_SAMPL_TIME             1052
#define IDC_COMMENT                     1052
#define IDC_RING_1_BEF                  1052
#define IDC_EDIT2                       1053
#define IDC_PLUS_B                      1053
#define IDC_CURVALUE_LIMIT              1053
#define IDC_COMPANY                     1053
#define IDC_ENER_E2_VALUE               1053
#define IDC_CHANNEL0_G2S                1053
#define IDC_EDIT_END_FILE               1053
#define IDC_EDIT_REPEAT_NUM             1053
#define IDC_RING_1_BACK                 1053
#define IDC_EDIT3                       1054
#define IDC_PLUS_C                      1054
#define IDC_PASSWORD                    1054
#define IDC_CHANNEL1_ALL                1054
#define IDC_END_POINT                   1054
#define IDC_EDIT_PEAK                   1054
#define IDC_EDIT_ABCD_MODIFY            1054
#define IDC_RING_4_BEF                  1054
#define IDC_EDIT4                       1055
#define IDC_OFFSET_Y                    1055
#define IDC_ENER_E1_VALUE               1055
#define IDC_CHANNEL1_G2S                1055
#define IDC_MANULMODITY_EDIT            1055
#define IDC_RING_4_BACK                 1055
#define IDC_POS_UPLIMIT                 1055
#define IDC_EDIT5                       1056
#define IDC_PLUS_D                      1056
#define IDC_CHANNEL2_ALL                1056
#define IDC_RING_3_BEF                  1056
#define IDC_EDIT6                       1057
#define IDC_OFFSET_E                    1057
#define IDC_CHANNEL2_G2S                1057
#define IDC_RING_3_BACK                 1057
#define IDC_EDIT7                       1058
#define IDC_OFFSET_X                    1058
#define IDC_CHANNEL3_ALL                1058
#define IDC_RING_2_BEF                  1058
#define IDC_EDIT8                       1059
#define IDC_ETH_VALUE                   1059
#define IDC_CHANNEL3_G2S                1059
#define IDC_RING_2_BACK                 1059
#define IDC_EDIT9                       1060
#define IDC_TD_VALUE                    1060
#define IDC_CHANNEL4_ALL                1060
#define IDC_CORNER_BEF                  1060
#define IDC_POS_DOWNLIMIT               1060
#define IDC_RADIO1                      1061
#define IDC_CHIP_EEPROM                 1061
#define IDC_CHANNEL4_G2S                1061
#define IDC_NEW_FILEPACK                1061
#define IDC_CORNER_BACK                 1061
#define IDC_NEG_UPLIMIT                 1061
#define IDC_RADIO2                      1062
#define IDC_CHIP_ANOL                   1062
#define IDC_CHANNEL5_ALL                1062
#define IDC_EDIT_FILEPACK               1062
#define IDC_NEG_DOWNLIMIT               1062
#define IDC_RADIO3                      1063
#define IDC_CHIP_ALL                    1063
#define IDC_CHANNEL5_G2S                1063
#define IDC_TEMPER_UPLIMIT              1063
#define IDC_RADIO4                      1064
#define IDC_IOSEL_IN                    1064
#define IDC_CHANNEL6_ALL                1064
#define IDC_TEMPER_DOWNLIMIT            1064
#define IDC_RADIO5                      1065
#define IDC_IOSEL_OUT                   1065
#define IDC_CHANNEL6_G2S                1065
#define IDC_LOAD                        1065
#define IDC_WR_PARA                     1065
#define IDC_2D_SHOW_OFFSET2             1066
#define IDC_CHANNEL7_ALL                1066
#define IDC_UPLOAD_DATA                 1067
#define IDC_CHANNEL7_G2S                1067
#define IDC_POWERON_CHECK               1068
#define IDC_STATIC_POWERCHECK           1069
#define IDC_CHECK_SHOWBAR_READFILE      1070
#define IDC_SHOW_STATIC_SELFILE         1071
#define IDC_SHOW_BLOCK_SEL              1072
#define IDC_STATIC10                    1076
#define IDC_OUT                         1080
#define IDC_BUTTON1                     1081
#define IDC_SAVE_CUR_LIMIT              1081
#define IDC_BLOCAL_LOADDATA             1081
#define IDC_SET_ENER_INIT               1081
#define IDC_SET_TMOD_INIT               1081
#define IDC_QUIT_OUT                    1081
#define IDC_SAVE_PARA                   1081
#define IDC_CLEARSHOW                   1081
#define IDC_RENAME                      1081
#define IDC_EFFECT_RESOURCE_FILE        1081
#define IDC_LOAD_FILENAME               1081
#define IDC_AUTO_SAMPLE                 1081
#define IDC_SHOWMAP                     1081
#define IDC_VERSION_POLL                1081
#define IDC_CALCULATE_LIMIT             1082
#define IDC_REDRAW_LIMIT                1084
#define IDC_CHECK_X_Y                   1086
#define IDC_LIMIT_STAT                  1087
#define IDC_PROGRESS1                   1088
#define IDC_COMSET_MANUL_CHECK          1089
#define IDC_OPEN_LIMITTAB               1090
#define IDC_OFFSET1_ADD                 1094
#define IDC_OFFSET1_DEC                 1095
#define IDC_ENVIREN_STATE               1096
#define IDC_LOADFILE                    1097
#define IDC_STATIC_G2S                  1098
#define IDC_EN_MOVEWHOLELINE            1099
#define IDC_PEAK_VALE_STAT              1100
#define IDC_CHECK_VER_HOR               1101
#define IDC_CHANNEL_CHANGE_SEL          1104
#define IDC_CHECK1                      1108
#define IDC_STOP_QUERY                  1109
#define IDC_PARA_ANOL_PARA              1109
#define IDC_RING_2_CHECK                1109
#define IDC_CHECK_MIDFILTER             1110
#define IDC_PARA_TIMESERIER             1110
#define IDC_RING_4_CHECK                1110
#define IDC_RING_3_CHECK                1111
#define IDC_CORNER_CHECK                1112
#define IDC_MOD_STATUS                  1114
#define IDC_SHOW_COUNTER                1115
#define IDC_BUCKETNO                    1116
#define IDC_CHECK_LOCAL                 1118
#define IDC_CHECK_ANOL                  1119
#define IDC_CHECK_ENERGE                1120
#define IDC_CHECK_TSERIES               1121
#define IDC_DOWN                        1122
#define IDC_CHECK_CYSNUM                1123
#define IDC_CHECK_TIMEMODFY             1124
#define IDC_DATA_PARA                   1126
#define IDC_SEL_TYPE                    1127
#define IDC_EFFECENT_EVALUAT            1128
#define IDC_BUTTON2                     1129
#define IDC_EFFECT_DESTINATION_FILE     1129
#define IDC_ABCD_MODIFY                 1129
#define IDC_BUTTON_AUTO_SAMPLE          1129
#define IDC_BUTTON3                     1130
#define IDC_EFFECT_OUTTEXT_FILE         1130
#define IDC_SAVE_DATA                   1130
#define IDC_STATIC_SOURCE               1131
#define IDC_STATIC_DESTINATION          1132
#define IDC_STATIC_OUTTEXT              1133
#define IDC_CHECK_OUTRELATIVE_VALUE     1138
#define IDC_CHECK_PEAK_ANOLPARA_SEL     1139
#define IDC_STATIC_PEAK                 1140
#define IDC_STATIC_PATH                 1143
#define IDC_READ_DATA                   1144
#define IDC_STATIC_FRAME                1146
#define IDC_CHECK_TIME                  1148
#define IDC_CHECK_FUHE1                 1149
#define IDC_CHECK_FUHE2                 1150
#define IDC_CHECK_SDOT                  1151
#define IDC_CHECK_AUTOSAMPLE            1152
#define IDC_PARA_ENERGE_LIMIT           1153
#define IDC_PARA_POSITION_LIMIT         1154
#define IDC_PARA_TIMEMODFY              1156
#define IDC_PARA_CYSNUM                 1157
#define IDC_OFFSET_MODIFY               1158
#define IDC_MANUAL_MOD_PRE              1159
#define IDC_MANUAL_MOD                  1160
#define IDC_STATUS                      1161
#define IDC_RING_1_CHECK                1165
#define IDC_VOLTAGE_STATIC              1166
#define IDC_NEGVOLTAGE_STATIC           1167
#define IDC_PERSEND_SEL                 1167
#define IDC_RD_PARA                     1168
#define IDC_OPERATE                     1169
#define IDC_BKT_VER_SHOW                1170
#define ID_MENU_COMMSET                 32774
#define ID_MENU_DATA_SAMPLE             32775
#define IDC_MENU_DATASAMPLE             32775
#define ID_MENU_ENVIRMENTPARAM          32778
#define ID_MENU_BOARDLOCAL              32779
#define ID_MENU_BOARDENERG              32780
#define ID_MENU_TIMEMODFY               32781
#define ID_MENU_CYSNUM                  32782
#define ID_MENU_TSERIES                 32783
#define ID_MENU_ANLOG                   32784
#define IDC_MENU_ANOL                   32784
#define ID_MENU_FASTOPEN                32787
#define ID_BUTTON32792                  32792
#define IDC_MENU_SHOW64ENERGESPECT      32795
#define IDR_MENU_FPGACOUNT              32796
#define ID_MENU_LOAD32BK                32797
#define AFX_ID_VIEW_LP_EVALUATE         32798
#define ID_MENUITEM32799                32799
#define AFX_ID_VIEW_32BKLP_EVALUATE     32800
#define ID_MENU_32BUCKET_PEAK_STAT      32801
#define ID_MENU_32BK_PARA_MODIFY        32802
#define ID_MENU_32BK_PARA_MANUL_MODIFY  32803
#define ID_MENU_FASTOPEN32FILE          32804
#define IDC_MENU_ABOUTME                32805
#define ID_FASTOPEN32FILE_NEXT          32806
#define ID_FASTOPEN32FILE_LAST          32807
#define IDC_FILE_SAVE                   32811
#define IDC_FILE_SAVE_ENERGE_LIMIT      32812
#define ID_OUTPUT_32BKLP_EVALUATE       32813
#define IDR_MENU_ENVIRMENT_LIMIT        32814
#define IDC_FILE_OPEN                   57601
#define IDC_MENU_SAVEAS                 57604

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
