//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MCB.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PRINT_PRE                   101
#define IDR_MAINFRAME                   128
#define IDR_MCBTYPE                     129
#define IDD_DLGBAR                      130
#define IDD_PROGCTRL                    133
#define IDD_COM_SEL                     134
#define IDB_BITMAP_TOOLBAR              140
#define IDD_SET_HARDWARE_PARA           143
#define IDD_ENGERGE_KEDU                145
#define IDD_WIDTH_STAT                  146
#define IDD_COLORSET                    147
#define IDD_PARA_SET_USB                148
#define IDD_READ_FLASH_SEL              150
#define IDD_DLG_PRINT                   152
#define IDD_DIALOG1                     155
#define IDB_BITMAP3                     161
#define IDB_BITMAP4                     162
#define IDB_BITMAP1                     163
#define IDD_DIG_PR                      164
#define IDD_DIALOG2                     165
#define IDC_MCB_MODSEL                  1004
#define IDC_BUFF_MODSEL                 1005
#define IDC_CTL_START_SAMPLE            1008
#define IDC_CTL_STOP_SAMPLE             1009
#define IDC_RECEIVE_EXTERNAL_RAM        1010
#define IDC_CONTINUE_SAMPLE             1011
#define IDC_SEND_EXTERNAL_RAM           1016
#define IDC_COMM_OPEN_CLOSE             1018
#define IDC_TIMER_EDIT                  1019
#define IDC_INTREST_DAO_SHOW            1021
#define IDC_CHANEL_LR_LIMIT             1022
#define IDC_REALTIME_SEL                1023
#define IDC_LIVETIME_SEL                1024
#define IDC_RESET_SYSTEM                1027
#define IDC_COMTEST                     1028
#define IDC_FULLRAM_VIEWSEL             1029
#define IDC_EXPRAM_VIEWSEL              1030
#define IDC_COMBO_HOR                   1032
#define IDC_COMBO_VER                   1034
#define IDC_SHOW_REAL_LIVE_TIME         1035
#define IDC_QUERY_TIMEOUT               1036
#define IDC_QUERY_SAMPLE_STATE          1037
#define IDC_EXTERNALDATA_MCB2BUFF       1038
#define IDC_EDIT_PARA_X                 1039
#define IDC_EDIT_PARA_Y                 1040
#define IDC_EDIT_PARA_E                 1041
#define IDC_EDIT_PARA_ETH               1042
#define IDC_COMSEL                      1043
#define IDC_EDIT_PARA_A                 1043
#define IDC_EDIT_PARA_B                 1044
#define IDC_EDIT_PARA_C                 1045
#define IDC_EDIT_PARA_D                 1046
#define IDC_STATE_SHOW                  1046
#define IDC_CANCEL                      1047
#define IDC_WIDTH_STAT                  1049
#define IDC_STATIC_TEXT                 1050
#define IDC_STATIC_HOR                  1052
#define IDC_STATIC_GAIN                 1052
#define IDC_STATE_START_TIME            1054
#define IDC_SET_TIME_VALUE              1056
#define IDC_CHECK_TIME_MODE             1058
#define IDC_ENGER_KEDU_SLOPE            1059
#define IDC_ENGER_KEDU_OFFSET           1060
#define IDC_CHECK_ENGER_KEDU_UNIT       1061
#define IDC_COMB_DT                     1062
#define IDC_COMB_READY                  1063
#define IDC_COMB_ANWSER                 1064
#define IDC_COMB_ENADC                  1065
#define IDC_CHECK_CHANNEL_WIDTH         1070
#define IDC_IO_READ                     1071
#define IDC_IO_WRITE                    1072
#define IDC_COMB_DATA_POLARITY          1073
#define IDC_ENERGE_KEDU_VALUE           1074
#define IDC_WIDTH_VALUE                 1076
#define IDC_STATIC_UNIT                 1077
#define IDC_SHOW_REAL_TIME              1078
#define IDC_SHOW_LIVE_TIME              1079
#define IDC_SHOW_RATIO_TIME             1080
#define IDC_FULL_COLOR                  1081
#define IDC_EXP_COLOR                   1082
#define IDC_STATIC1                     1084
#define IDC_STATIC2                     1085
#define IDC_STATIC3                     1086
#define IDC_INTEREST_COLOR              1087
#define IDC_CHN_WIDTH                   1087
#define IDC_STATIC4                     1088
#define IDC_ETH_UP_USBADC               1088
#define IDC_SMALL_WINDOW_COLOR          1089
#define IDC_PORT_STATUS_SHOW            1089
#define IDC_ETH_DOWN_USBADC             1089
#define IDC_FLASH_SEL                   1090
#define IDC_TIME_UP_ETH                 1090
#define IDC_WR_FPGA                     1091
#define IDC_ANOL_SIGNAL_SEL             1091
#define IDC_WR_FLASH                    1092
#define IDC_DIGIT_SIGNAL_SEL            1092
#define IDC_TIME_DOWN_ETH               1093
#define IDC_READY_POL                   1095
#define IDC_RADIO_ALL                   1096
#define IDC_RADIO_PART                  1097
#define IDC_RADIO_SELF                  1098
#define IDC_EDIT_MIN                    1099
#define IDC_DEADTIME_POL                1100
#define IDC_EDIT_MAX                    1100
#define IDC_ANSWER_POL                  1101
#define IDC_BUTTON_PRE                  1101
#define IDC_ENADC_POL                   1102
#define IDC_BUTTON_CANCEL               1102
#define IDC_DATA_POL                    1103
#define IDC_CHECK1                      1105
#define IDC_CHECK2                      1106
#define IDC_CHECK3                      1107
#define IDC_CHECK4                      1108
#define IDC_CHECK5                      1109
#define IDC_CHECK6                      1110
#define IDC_CHECK7                      1112
#define IDC_CHECK9                      1114
#define IDC_RADIO1                      1115
#define IDC_RADIO_INTEREST              1115
#define IDC_RADIO2                      1116
#define IDC_RADIO3                      1117
#define IDC_EDIT1                       1118
#define IDC_EDIT2                       1119
#define IDC_COMBO1                      1120
#define IDC_EDIT3                       1121
#define IDC_RADIO4                      1122
#define IDC_RADIO_AUTOSELECT            1122
#define IDC_RADIO5                      1123
#define IDC_RADIO_SELFSELECT            1123
#define IDC_SOURCE                      1129
#define IDC_COMBOX_EGUNIT               1130
#define IDC_COMBO_EXP_HOR               1134
#define IDC_COMBO_EXP_VER               1135
#define IDC_STATIC_CHANNEL              1136
#define IDC_STATIC_COUNT                1137
#define IDC_SCROLLBAR3                  1145
#define IDC_STATIC_TIME                 1146
#define IDC_STATIC_TEST                 1147
#define IDC_STATIC_TIMEUNIT             1148
#define IDC_STATIC_GAIN_VER             1149
#define IDC_STATIC_HORI                 1150
#define IDC_STATIC_HOR_VER              1151
#define IDC_STATIC_QUERY                1152
#define IDC_STATIC_HARDSTATE            1153
#define ID_MENU_FILE_OPEN               32771
#define ID_MENU_FILE_SAVE_AS            32772
#define AFX_ID_PROGCTRL                 32773
#define AFX_ID_SET_COMMPORT             32775
#define AFX_ID_STARTSAMPLE              32776
#define AFX_ID_STOPSAMPLE               32777
#define AFX_ID_RESETSAMPLE              32778
#define AFX_ID_TESTSAMPLE               32779
#define AFX_ID_CONTINUESAMPLE           32780
#define AFX_ID_RECEIVESAMPLE            32781
#define ID_MENUITEM32786                32786
#define AFX_ID_WHOLEDATA_FILTER         32786
#define ID_MENUITEM32787                32787
#define AFX_ID_INTEREST_SUM             32787
#define ID_MENUITEM32788                32788
#define AFX_ID_WHOLEDATA_SUM            32788
#define ID_MENUITEM32789                32789
#define AFX_ID_OUT_REPORT               32789
#define AFX_ID_SENDSAMPLE               32790
#define AFX_ID_LINE_POINT_SEL           32791
#define AFX_ID_CLEAR_BUFF               32792
#define AFX_ID_HARDWARE_PARA_SET        32793
#define AFX_ID_ENERGE_KEDU              32794
#define AFX_ID_WIDTH_STAT               32795
#define AFX_ID_MCB_HELP                 32796
#define AFX_ID_LOG_LINE_SEL             32797
#define AFX_ID_LOG_SHOW                 32797
#define AFX_ID_LINE_SHOW                32803
#define AFX_ID_COLOR_SET                32804
#define ID_BLANK                        32807
#define ID_CONTINUE                     32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
